AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ProjectId:
    Type: String
    Description: AWS projectID to be used to associate ressources.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC id.
  
  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: VPC security groups ids.
  
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC subnet ids.
  
Outputs:
  LambdaFunction:
    Description: Information about the value
    Value: !GetAtt CodePipelineNotify.Arn
    Export:
      Name: !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaFunction']]

Resources:
  CodePipelineNotify:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Environment: 
        Variables:
          SSM_PATH: !Ref 'ProjectId'
      VpcConfig:
        SecurityGroupIds: !Ref 'VpcSecurityGroupIds'
        SubnetIds: !Ref 'VpcSubnetIds'
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]

  CodePipelineNotifySNSLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref CodePipelineNotifySNSTopic
      FunctionName: !GetAtt
        - CodePipelineNotify
        - Arn

  CodePipelineNotifySNSCWPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowCloudWatchSNSTopic
          Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action: sns:Publish
          Resource: "*"
      Topics:
        - !Ref CodePipelineNotifySNSTopic

  CodePipelineNotifySNSTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - 
          Endpoint: !GetAtt 
            - CodePipelineNotify
            - Arn
          Protocol: "lambda"
      TopicName: "codepipeline-notify"

  CodePipelineNotifyEvents:
    Type: AWS::Events::Rule
    Properties:
      Description: Event rule for CodePipeline events
      EventPattern:
        source:
          - aws.codepipeline
      State: ENABLED
      Targets:
        - Arn: !Ref CodePipelineNotifySNSTopic
          Id: !Ref CodePipelineNotify

  CodePipelineNotifyDynamoDBRole: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [ !Ref ProjectId, "dynamodb" ] ]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:DescribeTable"
            Resource:
              - !GetAtt CodePipelineNotifyDynamoDBTable.Arn
      Roles: 
        - 
          Fn::ImportValue: !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]

  CodePipelineNotifyDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Pipeline"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Pipeline"
          KeyType: "HASH"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref ProjectId
      GlobalSecondaryIndexes: 
        - 
          IndexName: "GlobalPipelineIndex"
          KeySchema: 
            - 
              AttributeName: "Pipeline"
              KeyType: "HASH"
          Projection: 
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes: 
        - 
          IndexName: "LocalPipelineIndex"
          KeySchema: 
            - 
              AttributeName: "Pipeline"
              KeyType: "HASH"
          Projection: 
            ProjectionType: "INCLUDE"